### ISSUE TITLE
Should add support to control clock speed

### ISSUE THREAD

**Issue by flagxor** [flagxor/ueforth#22]
Currently this is hard coded in Arduino UI. Can it be dynamic?

Potential interface to use:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/power_management.html

**Comment by snowyu** [comment]
Ref: https://github.com/silverchris/esphome/tree/auto-sleep/esphome/components/pm

```yml
esphome:
  name: $devicename
  platform: ESP32

# Enable logging
logger:

# Enable Home Assistant API
api:

pm:
  min_freq_mhz: 40
  max_freq_mhz: 80
  tickless: True
```
